function normalize(value=''){return String(value).toLowerCase().replace(/the international/g,'ti').replace(/season/g,'s').replace(/[^a-z0-9]+/g,' ').trim();}
function tokens(value){return new Set(normalize(value).split(/\s+/).filter(Boolean));}
function similarity(a,b){const left=tokens(a),right=tokens(b);if(!left.size||!right.size)return 0;return[...left].filter(x=>right.has(x)).length/Math.max(left.size,right.size);}
function date(value,end=false){return value?Date.parse(`${value}T${end?'23:59:59':'00:00:00'}Z`):NaN;}
function overlap(a,b){const as=date(a.startDate),ae=date(a.endDate||a.startDate,true),bs=date(b.startDate),be=date(b.endDate||b.startDate,true);return[as,ae,bs,be].every(Number.isFinite)&&as<=be+7*86400000&&bs<=ae+7*86400000;}
function sameYear(a,b){const ay=String(a.startDate||'').slice(0,4),by=String(b.startDate||'').slice(0,4);return Boolean(ay&&by&&ay===by);}
export function scoreProviderCandidate(event,candidate){if(!candidate?.leagueId)return{score:0,reasons:['candidate has no league ID']};if(candidate.providerIdAuthoritative)return{score:100,reasons:['authoritative provider link on tournament page']};const exact=normalize(event.name)===normalize(candidate.name),ratio=similarity(event.name,candidate.name);let score=exact?60:Math.round(ratio*45);const reasons=[exact?'exact normalized name':`name similarity ${Math.round(ratio*100)}%`];if(overlap(event,candidate)){score+=25;reasons.push('date ranges overlap');}if(sameYear(event,candidate)){score+=10;reasons.push('same year');}const expected=Number(event.participantCount||event.knownTeams||0),known=Number(candidate.knownTeams||candidate.participants?.length||0);if(expected&&known&&expected===known){score+=5;reasons.push('participant count matches');}return{score:Math.min(100,score),reasons};}
export function providerResolutionFor(event,candidates=[]){if(event.leagueId)return{providerIdState:'resolved',providerIdCandidate:String(event.leagueId),providerIdConfidence:100,providerIdReason:'Tournament already has a verified league ID',providerIdSource:event.provider||'catalog'};const ranked=candidates.map(candidate=>({candidate,...scoreProviderCandidate(event,candidate)})).sort((a,b)=>b.score-a.score),best=ranked[0];if(!best)return{providerIdState:'unresolved',providerIdCandidate:null,providerIdConfidence:0,providerIdReason:'No provider candidates are currently available'};const ambiguous=Boolean(ranked[1]&&best.score-ranked[1].score<10&&String(best.candidate.leagueId)!==String(ranked[1].candidate.leagueId));return{providerIdState:best.score>=85&&!ambiguous?'candidate':'unresolved',providerIdCandidate:String(best.candidate.leagueId),providerIdCandidateName:best.candidate.name,providerIdConfidence:best.score,providerIdReason:ambiguous?'Top candidates are too close to resolve safely':best.reasons.join(', '),providerIdSource:best.candidate.provider||'provider discovery',providerIdEvidence:best.candidate.providerIdEvidence||null};}
export function providerResolutionDiagnostics(event,candidates=[]){
  const ranked=candidates.filter(candidate=>candidate?.leagueId).map(candidate=>({leagueId:String(candidate.leagueId),name:candidate.name||`League ${candidate.leagueId}`,source:candidate.provider||'provider discovery',...scoreProviderCandidate(event,candidate)})).sort((a,b)=>b.score-a.score).slice(0,3);
  const resolution=providerResolutionFor(event,candidates);
  return{...resolution,providerIdBestRejectedName:resolution.providerIdState==='unresolved'?(ranked[0]?.name||null):null,providerIdBestRejectedLeagueId:resolution.providerIdState==='unresolved'?(ranked[0]?.leagueId||null):null,providerIdBestRejectedConfidence:resolution.providerIdState==='unresolved'?(ranked[0]?.score||0):null,providerIdAlternatives:ranked};
}
export function annotateProviderResolution(events,candidates){return events.map(event=>({...event,...providerResolutionDiagnostics(event,candidates)}));}
