import { config } from '../config.js';
import { fetchJson } from '../utils.js';
import { getOpenDotaMatch, getVerifiedSeriesContext, normalizeOpenDotaMatch } from './opendota.js';
import { normalizeSeriesFormat, seriesProgress } from '../seriesFormat.js';
function leagueId(context){const value=String(context?.leagueId||'');if(!value)throw new Error('Tournament league ID is unavailable');return value;}
export async function getLiveLeagueGames(context){
  if(!config.steamApiKey)return [];
  const id=leagueId(context),url=new URL('https://api.steampowered.com/IDOTA2Match_570/GetLiveLeagueGames/v1/');
  url.searchParams.set('key',config.steamApiKey);url.searchParams.set('league_id',id);
  const data=await fetchJson(url);return(data?.result?.games||[]).filter(game=>String(game.league_id)===id);
}
export async function getMatchDetails(matchId){if(!config.steamApiKey)return null;const url=new URL('https://api.steampowered.com/IDOTA2Match_570/GetMatchDetails/v1/');url.searchParams.set('key',config.steamApiKey);url.searchParams.set('match_id',String(matchId));return(await fetchJson(url))?.result||null;}
export function simplifyLiveGame(game){const board=game.scoreboard||{},rp=board.radiant?.players||[],dp=board.dire?.players||[],worth=p=>p.reduce((s,x)=>s+Number(x.net_worth??x.gold??0),0),lineup=p=>p.map(x=>({name:x.name||x.personaname||null,accountId:x.account_id==null?null:String(x.account_id),heroId:x.hero_id??null,netWorth:Number(x.net_worth??x.gold??0)}));return{matchId:String(game.match_id),leagueId:String(game.league_id||''),radiant:game.team_name_radiant||game.radiant_team?.team_name||'Radiant',dire:game.team_name_dire||game.dire_team?.team_name||'Dire',seriesId:game.series_id?String(game.series_id):null,seriesType:game.series_type??null,seriesFormat:normalizeSeriesFormat({seriesType:game.series_type}),radiantSeriesWins:Number(game.radiant_series_wins??game.series_score_radiant??0),direSeriesWins:Number(game.dire_series_wins??game.series_score_dire??0),radiantScore:board.radiant?.score??0,direScore:board.dire?.score??0,gameTime:Number(board.duration??game.delay??0),radiantNetWorth:worth(rp),direNetWorth:worth(dp),radiantLineup:lineup(rp),direLineup:lineup(dp),seriesProgress:seriesProgress({scoreA:Number(game.radiant_series_wins??0),scoreB:Number(game.dire_series_wins??0),format:normalizeSeriesFormat({seriesType:game.series_type})}),lastSeenAt:Date.now(),missingPolls:0,status:'active'};}
export async function getRichMatchDetails(matchId){try{const valve=await getMatchDetails(matchId);if(valve&&typeof valve.radiant_win==='boolean'){try{return await normalizeOpenDotaMatch(await getOpenDotaMatch(matchId));}catch{return{matchId:String(matchId),radiant:valve.radiant_name||'Radiant',dire:valve.dire_name||'Dire',radiantWin:Boolean(valve.radiant_win),radiantScore:valve.radiant_score??0,direScore:valve.dire_score??0,duration:valve.duration??0,seriesId:valve.series_id?String(valve.series_id):null,top:null,radiantDraft:[],direDraft:[],largestLead:null};}}}catch(error){if(!String(error.message).includes('HTTP 500'))console.warn(`Valve details failed for ${matchId}: ${error.message}`);}return normalizeOpenDotaMatch(await getOpenDotaMatch(matchId));}
export async function getRecentLeagueMatches(context,limit=5){if(!config.steamApiKey)return[];const id=leagueId(context),url=new URL('https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/v1/');url.searchParams.set('key',config.steamApiKey);url.searchParams.set('league_id',id);url.searchParams.set('matches_requested',String(Math.max(limit,10)));const data=await fetchJson(url),result=[];for(const item of(data?.result?.matches||[]).slice(0,limit)){try{const match=await getRichMatchDetails(item.match_id);if(!match.leagueId||String(match.leagueId)===id)result.push({...match,status:'completed'});}catch(error){console.warn(`Match ${item.match_id} is not ready: ${error.message}`);}}return result;}
export async function getVerifiedMatchAndSeries(matchId){const match=await getRichMatchDetails(matchId);let series=null;try{series=await getVerifiedSeriesContext(match);}catch(error){console.warn(`Series ${match.seriesId||'unknown'} unavailable: ${error.message}`);}return{match,series};}
