import { config } from '../config.js';
import { fetchJson } from '../utils.js';
const endpoint='https://www.dota2.com/webapi/IDOTA2League/GetLeagueData/v001';
const cache=new Map();
function idOf(context){const id=String(context?.leagueId||'');if(!id)throw new Error('Tournament league ID is unavailable');return id;}
export async function getLeagueData(context){const id=idOf(context),existing=cache.get(id);if(existing&&existing.expires>Date.now())return existing.value;const url=new URL(endpoint);url.searchParams.set('league_id',id);const value=await fetchJson(url,{headers:{Accept:'application/json','User-Agent':'Dota-Tier1-Tournament-Bot/2.2.0'}});cache.set(id,{value,expires:Date.now()+config.scheduleRefreshMinutes*60000});return value;}
function objects(value,result=[]){if(!value||typeof value!=='object')return result;if(!Array.isArray(value))result.push(value);for(const child of Object.values(value))if(child&&typeof child==='object')objects(child,result);return result;}
function first(obj,names){for(const name of names)if(obj[name]!=null)return obj[name];return null;}
function epoch(value){const n=Number(value);return Number.isFinite(n)&&n>=1e9?new Date(n>9999999999?n:n*1000).toISOString():null;}
function teamMap(data){const map=new Map();for(const o of objects(data)){const id=first(o,['team_id','teamId']),name=first(o,['team_name','teamName','name']);if(id&&name&&!String(name).toLowerCase().includes('match'))map.set(String(id),String(name));}return map;}
function teamName(node,side,teams){const direct=first(node,[`${side}_team_name`,`${side}TeamName`,`team_${side}_name`]);if(direct)return String(direct);const id=first(node,[`${side}_team_id`,`${side}TeamId`,`team_${side}_id`]);return id&&teams.has(String(id))?teams.get(String(id)):null;}
export async function getLeagueSchedule(context){const data=await getLeagueData(context),teams=teamMap(data),seen=new Set(),rows=[];for(const node of objects(data)){const beginAt=epoch(first(node,['scheduled_time','start_time','start_timestamp','timestamp','begin_at']));if(!beginAt)continue;const radiant=teamName(node,'radiant',teams)||teamName(node,'team_one',teams)||first(node,['team1_name','team_1_name']),dire=teamName(node,'dire',teams)||teamName(node,'team_two',teams)||first(node,['team2_name','team_2_name']),name=first(node,['name','node_name','match_name']);if(!radiant&&!dire&&!name)continue;const id=String(first(node,['match_id','series_id','node_id','id'])||`${beginAt}:${name||radiant}:${dire}`);if(seen.has(id))continue;seen.add(id);rows.push({id,leagueId:idOf(context),beginAt,teams:[String(radiant||'TBD'),String(dire||'TBD')],name:String(name||''),stage:String(first(node,['stage','round_name','phase'])||name||'Tournament series'),status:String(first(node,['state','status'])||'scheduled').toLowerCase(),bestOf:Number(first(node,['best_of','series_type','games_to_win'])||0)||null,source:'Valve League Data'});}return rows.sort((a,b)=>Date.parse(a.beginAt)-Date.parse(b.beginAt));}
export async function getLeagueTeams(context){const data=await getLeagueData(context);return[...teamMap(data).entries()].map(([teamId,name])=>({teamId,name}));}
export async function getLeagueStandings(){return[];}
