import fs from 'node:fs/promises';import path from 'node:path';import{fileURLToPath}from'node:url';import{EmbedBuilder}from'discord.js';import{getTrackedMatches,getSetting}from'./db.js';import{discoverySummary}from'./tournaments/discoveryService.js';import{preparationSummary}from'./tournaments/preparationService.js';import{activationSummary}from'./tournaments/activationService.js';import{providerHealthSummary}from'./tournaments/providerHealth.js';import{listTournamentAdapters}from'./tournaments/workers/adapterRegistry.js';import{coverageRuntimeSummary}from'./tournaments/coverageRuntime.js';import{coverageWorkerSummary}from'./tournaments/workers/workerManager.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export function formatPreparationAge(value,now=Date.now()){const t=Date.parse(value||'');if(!Number.isFinite(t))return'not available';const m=Math.max(0,Math.floor((now-t)/60000)),d=Math.floor(m/1440),h=Math.floor((m%1440)/60);return d?`${d}d ${h}h`:h?`${h}h ${m%60}m`:`${m}m`;}
export async function diagnosticsEmbed(){let registry={teams:{}};try{registry=JSON.parse(await fs.readFile(path.join(root,'data','teams.json'),'utf8'));}catch{}const teams=Object.values(registry.teams||{}),tracked=getTrackedMatches(),discovery=discoverySummary(),prep=preparationSummary(),activation=activationSummary(),providers=providerHealthSummary(),coverage=coverageRuntimeSummary(),workers=coverageWorkerSummary(),adapters=listTournamentAdapters().map(a=>a.name).join(', ')||'none';return new EmbedBuilder().setColor(0x5865F2).setTitle('Bot Diagnostics').addFields(
{name:'Platform',value:'Catalog-driven Tier 1 runtime\nLegacy TI runtime: removed'},
{name:'Team identity',value:`${teams.length} teams\n${teams.filter(t=>t.logoFile).length} cached logos\n${teams.filter(t=>t.emojiId).length} application emojis`},
{name:'Processing',value:`${tracked.filter(x=>x.status==='active').length} active games\n${tracked.filter(x=>x.status==='result-unavailable').length} unavailable results`},
{name:'Discovery',value:`Catalog: ${discovery.total}\nActive: ${discovery.active.length} • Upcoming: ${discovery.upcoming.length}`},
{name:'Providers',value:(providers.map(p=>`${p.name}: ${p.status}${p.detail?` (${p.detail})`:''}`).join('\n')||'No checks completed')+`\nAdapters: ${adapters}`},
{name:'Preparation',value:`Ready: ${prep.ready}\nAwaiting provider ID: ${prep.awaitingProviderId}\nAwaiting teams: ${prep.awaitingTeams}\nScheduled: ${prep.scheduled}\nRetry: ${prep.retry}\nLast cycle: ${prep.at||'not completed'}`},
{name:'Activation',value:`Active coverage: ${activation.activeCoverage}\nWaiting preparation: ${activation.waitingPreparation}\nBlocked: ${activation.blocked}\nCompleted: ${activation.completedCoverage}\nLast cycle: ${activation.at||'not completed'}`},
{name:'Coverage runtime',value:`Running: ${coverage.running}\nStarted this cycle: ${coverage.started}\nStopped this cycle: ${coverage.stopped}\nLast reconcile: ${coverage.at||'not completed'}`},
{name:'Generic workers',value:`Observing: ${workers.observing}\nPublishing: ${workers.running}\nDegraded: ${workers.degraded||0}\nAwaiting adapter: ${workers.waitingAdapter}\nLast reconcile: ${workers.at||'not completed'}`},
{name:'Legacy archive messages',value:`Bracket: ${getSetting('bracket_message_id')?'stored':'not stored'}\nSeries: ${getSetting('series_overview_message_id')?'stored':'not stored'}`}
).setTimestamp();}
